### ISSUE TITLE
readme.md ergänzen

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/hyphenator#1]

**Comment by schuer** [comment]
Erledigt.

**Comment by phoebusryan** [comment]
Danke. Die Sektion 'Probleme' habe ich allerdings direkt im Addon gelöst:
https://github.com/FriendsOfREDAXO/hyphenator/blob/master/lib/class.hyphenator.php#L44-L48

Keine Ahnung, ob das toll ist. Ich wollte aber nicht jedem den Hack aufdrängen.

**Comment by schuer** [comment]
Hast recht. Ich hatte die README gestern noch mit der Info angepasst und committet, sie im Nachgang aber unbemerkt wieder per force push zurückgesetzt, als ich eigentlich nur die Tags pushen wollte.

Habe es jetzt wieder ergänzt. Kannst aber gern nochmal weiter anpassen, ist ja maßgeblich dein Addon :)
