### ISSUE TITLE
Fehlerhafte Umbrüche auf Mobilgeräten

### ISSUE THREAD

**Issue by iamjonasmarlo** [FriendsOfREDAXO/hyphenator#10]
Leider stellen wir Mobilgeräte (in meinem Fall in iPhone 8+) fehlerhafte Umbrüche dar (siehe Screenshot). Wörter werden nicht mehr vollständig angezeigt, sondern umbrechen viel früher. Das seltsame ist, dass die Umbrüche auf dem Desktop bei einem skalierten Browserfenster korrekt angezeigt werden.

![screen](https://user-images.githubusercontent.com/8004195/47089114-57492d00-d220-11e8-915b-9f5fab1db384.jpg)

Ist der Fehler bekannt? Gibt es vielleicht schon eine Lösung?

**Comment by phoebusryan** [comment]
Habs mir gerade angeschaut und es liegt hier dran:
https://github.com/FriendsOfREDAXO/hyphenator/blob/master/lib/class.hyphenator.php#L46

Kommentier die Zeile mal aus in deinem Code. Früher war der Fix notwendig; heute schadet er wohl.

**Comment by iamjonasmarlo** [comment]
Das scheint es gewesen zu sein! Danke für die schnelle Hilfe!
