### ISSUE TITLE
"Min. Links" in der Config wird nicht beachtet, oder nur zum Teil

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/hyphenator#11]
Ich weiss, evtl. ist das Addon bald obsolet, aber ich verwende es wegen des mangelnden Browser-Supports, vor allem in Bezug auf die deutsche Rechtschreibung, praktisch in jedem Projekt und finde es grossartig.

Allerdings habe ich gerade den Fall, dass die Grafikerin gerne hätte, das erst ab dem 4. Buchstaben links getrennt wird (was ich auch so eingestellt habe, links 4, rechts 2, minimal Wortlänge default 6). 

**Sprich folgende Wörter sollten nur wie folgt getrennt werden dürfen:**
Kur­siv­ge­birges -> Kur­siv•­ge•­birges
Hei­mat­stadt -> Hei­mat­•stadt

**Allerdings wird momentan so getrennt:**
Kur•­­siv•­ge•­birges
Hei•­­mat­•­stadt

Eine Ahnung woran das liegen könnte?

**Comment by ynamite** [comment]
Miau

**Comment by ynamite** [comment]
Hallo Echo ...

**Comment by polarpixel** [comment]
Kann ich bestätigen. Ich habe in den Einstellungen "Min. links: 4", "Min rechts: 4", "Min.Wortlänge: 9" hinterlegt. Trotzdem habe ich Trennungen wie "soll-te" oder "An-satz". Lösung wäre toll. :-)

**Comment by polarpixel** [comment]
Ah, Kommando zurück, zumindest was meinen Post betrifft. Ich hatte noch im CSS zusätzlich hyphens angeschaltet, das kollidierte natürlich. Also bei mir scheint es korrekt zu funktionieren.

**Comment by ynamite** [comment]
Naja, ist ja auch zwei Jahre her ... seither gab's ein Update. Keine Ahnung ob das Problem noch besteht 🤷
