### ISSUE TITLE
Nutzen?

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/hyphenator#5]
In Zeiten von CSS Hyphenation, bleibt die Frage: Hat eine JS oder PHP Lösung irgend einen Vorteil oder eine Daseinsberechtigung? (Kein Angriff, ernstgemeinte Frage)

**Comment by phoebusryan** [comment]
Die Browserkompatiblität ist mit der PHP-Lösung höher ;)

**Comment by AWqxKAWERbXo** [comment]
Kennt jemand den Stand 2019?
https://caniuse.com/#search=Hyphenation

Kann man ohne weiteres auf die browsereigene Lösung setzen?

**Comment by hirbod** [comment]
Ich würde sagen: definitiv ja :)

**Comment by AWqxKAWERbXo** [comment]
Add-on archivieren?

**Comment by phoebusryan** [comment]
Der Vorteil an dem Addon ist, dass es aufgrund von Wörterbüchern trennt. Das CSS-Attribut macht das ja nicht.

**Comment by hirbod** [comment]
@phoebusryan woher kommt diese Annahme? CSS nutzt natürlich interne Wörterbücher, die Steuerung hierzu kommt durch das `lang="de/en/...."` im `<html>`  tag

**Comment by phoebusryan** [comment]
Ist das so? Wenn ja, hätte sich das Addon tatsächlich erledigt. Hast du eine Quelle?

**Comment by hirbod** [comment]
https://developer.mozilla.org/de/docs/Web/CSS/hyphens

**Comment by hirbod** [comment]
Und hier noch ein weiterer Artikel, wie gut sich das mittlerweile sogar konfigurieren lässt.
https://medium.com/clear-left-thinking/all-you-need-to-know-about-hyphenation-in-css-2baee2d89179

**Comment by phoebusryan** [comment]
Interessant. Muss ich mir mal alles durchlesen. Danke für die Info.

**Comment by phoebusryan** [comment]
Also das sehe ich ganz anders. Habs grade mal getestet und es funktioniert bei der Hälfte der Browser gar nicht oder nicht zuverlässig. Der neuste Chrome unterstützt es gar nicht.
https://caniuse.com/#search=hyphens

**Comment by hirbod** [comment]
Der neuste Chrome kann das natürlich. Es steht da partial und er kann bisher nur "auto", aber das ist in 99,9% der Fälle absolut ausreichend. Anyway, deine Entscheidung ob du das AddOn nutzen/pflegen möchtest, wir kommen mit der CSS-only Lösung vollkommen zurecht. Teilweise sind noch Vendor-Prefixes notwendig.

**Comment by hirbod** [comment]
Tatsächlich scheint es auf dem Chrome für Windows aktuell zu buggen bzw gar nicht zu funktionieren.

**Comment by schuer** [comment]
> Tatsächlich scheint es auf dem Chrome für Windows aktuell zu buggen bzw gar nicht zu funktionieren.

Chrome unterstützt hyphens aktuell nur auf Android und Mac. Windows ist noch nicht implementiert, siehe Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=652964

**Comment by hirbod** [comment]
Dann ist das Addon sicherlich noch sehr nützlich.
